social_media_analytics:
  target: dev
  outputs:

    # ── Local development — DuckDB (fast, no server needed) ────────────────
    dev:
      type: duckdb
      path: "/tmp/social_media_analytics.duckdb"
      threads: 4
      extensions:
        - httpfs      # For reading Parquet from MinIO/S3

    # ── Production — DuckDB reading from MinIO ────────────────────────────
    prod:
      type: duckdb
      path: "/tmp/social_media_analytics_prod.duckdb"
      threads: 8
      settings:
        s3_endpoint: "minio:9000"
        s3_access_key_id: "minioadmin"
        s3_secret_access_key: "minioadmin"
        s3_use_ssl: false
        s3_url_style: path
